<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0"
	xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
	xmlns:fo="http://www.w3.org/1999/XSL/Format">
	<!-- Attribute used for table border -->
	<xsl:attribute-set name="tableBorder">
		<xsl:attribute name="border">solid 0.1mm black</xsl:attribute>
	</xsl:attribute-set>
	<xsl:template match="OrderItemData">
		<fo:root>
			<fo:layout-master-set>
				<fo:simple-page-master master-name="simpleA4"
					page-height="29.7cm" page-width="25.0cm" margin="1cm">
					<fo:region-body />
				</fo:simple-page-master>
			</fo:layout-master-set>
			<fo:page-sequence master-reference="simpleA4">
<!--				<fo:flow flow-name="xsl-region-after">-->
<!--					<fo:block font-size="6pt">-->
<!--						Generated by Increff-->
<!--					</fo:block>-->
<!--				</fo:flow>-->
				<fo:flow flow-name="xsl-region-body">
					<fo:block font-size="30pt" font-family="Helvetica"
						color="black" font-weight="bold" space-after="10mm" space-before="20pt">
						Invoice
					</fo:block>
					<fo:block font-size="16pt" font-family="Helvetica"
							  color="black" font-weight="bold" space-after="10mm" space-before="20pt">
						Order Id: <fo:inline font-weight="normal"><xsl:value-of select="orderId"/></fo:inline>

					</fo:block>
					<fo:block font-size="16pt" font-family="Helvetica"
							  color="black" font-weight="bold" space-after="10mm" space-before="20pt">
						Date: <fo:inline font-weight="normal"><xsl:value-of select="date"/></fo:inline>
					</fo:block>
					<fo:block font-size="12pt" space-before="30pt">
						<fo:table table-layout="fixed" width="100%"
							border-collapse="separate" line-height="25px">
							<fo:table-column column-width="4cm" />
							<fo:table-column column-width="4cm" />
							<fo:table-column column-width="4cm" />
							<fo:table-column column-width="5cm" />
							<fo:table-column column-width="4cm" />

							<fo:table-header>
								<fo:table-cell
									xsl:use-attribute-sets="tableBorder" padding-left="5pt">
									<fo:block font-weight="bold" padding-left="5pt">Barcode</fo:block>
								</fo:table-cell>
								<fo:table-cell
									xsl:use-attribute-sets="tableBorder">
									<fo:block font-weight="bold">Quantity</fo:block>
								</fo:table-cell>
								<fo:table-cell
										xsl:use-attribute-sets="tableBorder">
									<fo:block font-weight="bold">MRP</fo:block>
								</fo:table-cell>
								<fo:table-cell
										xsl:use-attribute-sets="tableBorder">
									<fo:block font-weight="bold">Selling Price(per Unit)</fo:block>
								</fo:table-cell>
								<fo:table-cell
										xsl:use-attribute-sets="tableBorder">
									<fo:block font-weight="bold">Total Selling Price</fo:block>
								</fo:table-cell>
							</fo:table-header>
							<fo:table-body>
								<xsl:apply-templates select="OrderItem" />
								<fo:table-row>
									<fo:table-cell xsl:use-attribute-sets="tableBorder">
										<fo:block>
											<fo:inline font-weight="bold">Total</fo:inline>
										</fo:block>
									</fo:table-cell>
									<fo:table-cell xsl:use-attribute-sets="tableBorder">
										<fo:block>
											<fo:inline font-weight="normal"><xsl:value-of select="totalQuantity"/></fo:inline>
										</fo:block>
									</fo:table-cell>
									<fo:table-cell xsl:use-attribute-sets="tableBorder">
										<fo:block>
											-
										</fo:block>
									</fo:table-cell>
									<fo:table-cell xsl:use-attribute-sets="tableBorder">
										<fo:block>
											-
										</fo:block>
									</fo:table-cell>
									<fo:table-cell xsl:use-attribute-sets="tableBorder">
										<fo:block>
											<fo:inline font-weight="normal"><xsl:value-of select="totalAmount"/></fo:inline>
										</fo:block>
									</fo:table-cell>
								</fo:table-row>
							</fo:table-body>
						</fo:table>
					</fo:block>
				</fo:flow>

			</fo:page-sequence>
		</fo:root>
	</xsl:template>
	<xsl:template match="OrderItem">
		<fo:table-row>
			<fo:table-cell xsl:use-attribute-sets="tableBorder">
				<fo:block>
					<xsl:value-of select="barcode" />
				</fo:block>
			</fo:table-cell>
			<fo:table-cell xsl:use-attribute-sets="tableBorder">
				<fo:block>
					<xsl:value-of select="quantity" />
				</fo:block>
			</fo:table-cell>
			<fo:table-cell xsl:use-attribute-sets="tableBorder">
				<fo:block>
					<xsl:value-of select="mrp" />
				</fo:block>
			</fo:table-cell>
			<fo:table-cell xsl:use-attribute-sets="tableBorder">
				<fo:block>
					<xsl:value-of select="perUnitSellingPrice" />
				</fo:block>
			</fo:table-cell>
			<fo:table-cell xsl:use-attribute-sets="tableBorder">
				<fo:block>
					<xsl:value-of select="totalSellingPrice" />
				</fo:block>
			</fo:table-cell>
		</fo:table-row>
	</xsl:template>
</xsl:stylesheet>